name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [jazzy, kilted]
    steps:
      - uses: ros-tooling/setup-ros@0.7.19
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}
      - uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: coresense_instrumentation coresense_instrumentation_driver coresense_instrumentation_interfaces coresense_instrumentation_rviz
          target-ros2-distro: ${{ matrix.ros_distro }}
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
